### ISSUE TITLE
#6ac083f Broke the extension

### ISSUE THREAD

**Issue by andrejsc** [zaggino/brackets-git#1317]
Informing you with a regret that commit #6ac083f (use cross-spawn) broke the extension on my fresh installation of Brackets.

**Error:**

Now on start I have a pop-up saying "... Cannot find module 'cross-spawn'".

**Temporary workaround:**

Checkout the source before the guilty commit: https://github.com/zaggino/brackets-git/tree/8ef52e930f3924279b20d3ce483a0703fc736fc3

**Comment by zaggino** [comment]
Have you tried running `npm install` in the extension directory?

**Comment by andrejsc** [comment]
It worked, but you have to mention this in installation procedures for Windows.

1. Install Node.js for Windows (it includes `npm`)
2. Extract brackets-git to extension folder
3. Open command-prompt and go into brackets-git extension folder
4. Type `npm install`
5. Execute/restart brackets

**Comment by zaggino** [comment]
That's really weird, I was 100% sure I included `node_modules` in the registry zip file...
